# This is a basic workflow to help you get started with Actions

name: Build and test

# Controls when the workflow will run
on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build package
        run: swift build -v

  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Smoke test package
        run: swift test -v

      - name: CINotify Email
        if: ${{ failure() }}
        uses: cinotify/github-action@v1.1.0
        with:
          # Recipient email address
          to: jhearst@protonmail.ch
          # Email subject
          subject: ScryfallKit failure
          # Email body
          body: A ScryfallKit test failed
